"""p27_export_fbx.py - T250 (P2.6): export stages + FBX of the player rig with a player-owned preset.

Input : work/player/rig/pl_r05_rigtest.blend (p25; opened by p26.build_export, never saved),
        work/goblin_swing/rig/data/export_preset.json (read only: the goblin preset copied into the player preset)
Output: work/player/rig/export/stage_rest.blend, stage_rigtest.blend (p26_export_stage.build_export)
        work/player/rig/export/Player.fbx          stage_rest    : armature `Player` + Player_mesh, no animation
        work/player/rig/export/Player@rigtest.fbx  stage_rigtest : armature `Player` + Player_mesh + action `rigtest`
        work/player/rig/data/export_preset.json    player-owned copy of the goblin preset (export kwargs, axis mapping
                                                   unity.x = -x, unity.y = z, unity.z = -y, blender_reimport options)
        unity/AvatarCheck/Assets/Player/Player.fbx, Player@rigtest.fbx (copies; the P1 Player@p1test.fbx + .meta are
                                                   removed so the Player@ clip set = rigtest)

CLI:  blender --background --factory-startup --python p27_export_fbx.py

Copied / adapted from work/goblin_swing/rig/scripts/s08_export_fbx.py (T35) and work/player/rig/scripts/p11_export.py
(T210: export_fbx, fbx_summary, reimport): the scene is renamed `rigtest` in memory for the clip file (the active-action
path names its single AnimStack after the scene). No club file (the player has no weapon mesh).
Self-check (stdout only): FBX header / node summary, reimport per file with the preset's reimport options (bones,
parents, bones connected by the importer), and for Player@rigtest.fbx the reimported bone world matrices (all bones
unconnected first, the goblin pitfall) vs the stage on every frame for key offsets 0 / 1 (max mm / deg).
"""
import copy
import hashlib
import json
import math
import shutil
import sys
from pathlib import Path

import bpy
from mathutils import Matrix

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import p26_export_stage as p26  # noqa: E402

RIG = HERE.parent
REPO = RIG.parents[2]
SRC_BLEND = RIG / "pl_r05_rigtest.blend"
GOBLIN_PRESET = REPO / "work" / "goblin_swing" / "rig" / "data" / "export_preset.json"
PRESET = RIG / "data" / "export_preset.json"
EXPORT = RIG / "export"
STAGE_REST = EXPORT / "stage_rest.blend"
STAGE_CLIP = EXPORT / "stage_rigtest.blend"
FBX_BODY = EXPORT / "Player.fbx"
FBX_CLIP = EXPORT / "Player@rigtest.fbx"
UNITY_DIR = REPO / "unity" / "AvatarCheck" / "Assets" / "Player"
UNITY_REMOVE = ("Player@p1test.fbx", "Player@p1test.fbx.meta")
ARM, MESH, CLIP = "Player", "Player_mesh", "rigtest"


def log(msg):
    print(f"[p27] {msg}")
    sys.stdout.flush()


def v3(v, nd=6):
    return [round(float(x), nd) + 0.0 for x in v]


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def mdiff(a, b):
    q = a.to_quaternion().conjugated() @ b.to_quaternion()
    ang = 2.0 * math.atan2(math.sqrt(q.x * q.x + q.y * q.y + q.z * q.z), abs(q.w))
    return (a.translation - b.translation).length * 1000.0, math.degrees(ang)


def write_preset():
    g = json.loads(GOBLIN_PRESET.read_text(encoding="utf-8"))
    p = {
        "_doc": "Player FBX export preset (T250), a player-owned copy of the goblin preset candidate A "
                "(work/goblin_swing/rig/data/export_preset.json, generated by s08_export_fbx.py). export_scene_fbx = "
                "keyword arguments passed to bpy.ops.export_scene.fbx for every file (bake_anim per file). axis_mapping "
                "matrices act on column vectors: v_out = M @ v_blender (rows = output axes).",
        "candidate": g.get("candidate"), "generated_by": "work/player/rig/scripts/p27_export_fbx.py",
        "copied_from": "work/goblin_swing/rig/data/export_preset.json", "blender_version": bpy.app.version_string,
        "export_scene_fbx": copy.deepcopy(g["export_scene_fbx"]),
        "files": {"Player.fbx": {"source_stage": "export/stage_rest.blend", "objects": [ARM, MESH], "bake_anim": False},
                  "Player@rigtest.fbx": {"source_stage": "export/stage_rigtest.blend", "objects": [ARM, MESH],
                                         "bake_anim": True}},
        "renames_in_memory": {"scene_for_clip": f"-> {CLIP} (AnimStack name of the active-action export)"},
        "scene_units": copy.deepcopy(g["scene_units"]),
        "axis_mapping": copy.deepcopy(g["axis_mapping"]),
        "blender_reimport": copy.deepcopy(g["blender_reimport"]),
    }
    PRESET.write_text(json.dumps(p, indent=1) + "\n", encoding="utf-8")
    return p


def select_only(objs):
    vl = bpy.context.view_layer
    for o in vl.objects:
        o.select_set(False)
    for o in objs:
        o.select_set(True)
    vl.objects.active = objs[0]
    return sorted(o.name for o in bpy.context.selected_objects)


def export_fbx(path, objs, bake_anim, kw_preset):
    sel = select_only(objs)
    kw = dict(kw_preset)
    kw["object_types"] = set(kw["object_types"])
    kw["bake_anim"] = bake_anim
    res = bpy.ops.export_scene.fbx(filepath=str(path), **kw)
    if res != {"FINISHED"}:
        raise RuntimeError(f"export_scene.fbx {path.name} returned {res}")
    sc = bpy.context.scene
    log(f"EXPORT {path.name}: selected {sel}, bake_anim {bake_anim}, scene {sc.name!r} frames {sc.frame_start}.."
        f"{sc.frame_end} @ {sc.render.fps} fps -> {res}; {path.stat().st_size} bytes, sha256 {sha(path)}")


def _child(e, id_):
    return next((c for c in e.elems if c.id == id_), None) if e is not None else None


def _p70(e):
    p = _child(e, b"Properties70")
    out = {}
    if p is not None:
        for c in p.elems:
            if c.id == b"P":
                out[c.props[0].decode()] = list(c.props[4:])
    return out


def _name(e):
    return e.props[1].split(b"\x00\x01")[0].decode()


def fbx_summary(path):
    from io_scene_fbx import parse_fbx
    root, ver = parse_fbx.parse(str(path))
    gs = _p70(_child(root, b"GlobalSettings"))
    hdr = {k: (gs[k][0] if k in gs and gs[k] else None) for k in
           ("UpAxis", "UpAxisSign", "FrontAxis", "FrontAxisSign", "CoordAxis", "CoordAxisSign",
            "UnitScaleFactor", "OriginalUnitScaleFactor", "TimeMode", "CustomFrameRate")}
    objs = _child(root, b"Objects")
    nodes, limbs, stacks, clusters, mats = [], [], [], 0, 0
    for e in objs.elems if objs is not None else []:
        if e.id == b"Model":
            kind = e.props[2].decode()
            if kind == "LimbNode":
                limbs.append(_name(e))
            else:
                p = _p70(e)
                nodes.append({"name": _name(e), "type": kind,
                              "lcl_rotation_deg": v3(p.get("Lcl Rotation", [0, 0, 0])[:3]),
                              "lcl_scaling": v3(p.get("Lcl Scaling", [1, 1, 1])[:3])})
        elif e.id == b"AnimationStack":
            stacks.append(_name(e))
        elif e.id == b"Deformer" and e.props[2] == b"Cluster":
            clusters += 1
        elif e.id == b"Material":
            mats += 1
    return {"fbx_version": ver, "header": hdr, "nodes": nodes, "limb_nodes": len(limbs),
            "limb_end_nodes": [n for n in limbs if n.endswith("_end")], "anim_stacks": stacks,
            "skin_clusters": clusters, "materials": mats}


def stage_world(path):
    bpy.ops.wm.open_mainfile(filepath=str(path), load_ui=False)
    sc = bpy.context.scene
    arm = bpy.data.objects[ARM]
    names = [b.name for b in arm.data.bones]
    parent = {b.name: (b.parent.name if b.parent else None) for b in arm.data.bones}
    out = {}
    for f in range(sc.frame_start, sc.frame_end + 1):
        sc.frame_set(f)
        out[f] = {n: (arm.matrix_world @ arm.pose.bones[n].matrix).copy() for n in names}
    return names, parent, out, (sc.frame_start, sc.frame_end)


def reimport(path, kw_import, names, parent, stage=None, rng=None):
    bpy.ops.wm.read_factory_settings(use_empty=True)
    res = bpy.ops.import_scene.fbx(filepath=str(path), **kw_import)
    log(f"REIMPORT {path.name}: import_scene.fbx {res}")
    arm = None
    for o in sorted(bpy.data.objects, key=lambda o: o.name):
        loc, rot, sc = o.matrix_world.decompose()
        log(f"  node {o.name!r} ({o.type}) parent {o.parent.name if o.parent else None!r}: world loc "
            f"{v3(loc * 1000.0, 4)} mm, rot {v3([math.degrees(a) for a in rot.to_euler()], 4)} deg, scale {v3(sc, 7)}")
        if o.type == "ARMATURE":
            arm = o
            bn = [b.name for b in o.data.bones]
            par_ok = all((o.data.bones[n].parent.name if o.data.bones[n].parent else None) == parent.get(n)
                         for n in bn if n in parent)
            log(f"  armature {o.name!r}: {len(bn)} bones, name set == stage {set(bn) == set(names)}, parents == stage "
                f"{par_ok}, connected by the importer {sum(1 for b in o.data.bones if b.use_connect)}")
        elif o.type == "MESH":
            me = o.data
            log(f"  mesh {o.name!r}: verts {len(me.vertices)}, polys {len(me.polygons)}, vertex groups "
                f"{len(o.vertex_groups)}, materials {len(me.materials)}, custom normals {me.has_custom_normals}")
    if stage is None or arm is None:
        return
    vl = bpy.context.view_layer
    vl.objects.active = arm
    bpy.ops.object.mode_set(mode="EDIT")
    for eb in arm.data.edit_bones:
        eb.use_connect = False
    bpy.ops.object.mode_set(mode="OBJECT")
    sc = bpy.context.scene
    for off in (0, 1):
        wp = wr = 0.0
        at = None
        for f in range(rng[0], rng[1] + 1):
            sc.frame_set(f + off)
            for n in names:
                p, r = mdiff(stage[f][n], arm.matrix_world @ arm.pose.bones[n].matrix)
                if p > wp or r > wr:
                    at = (n, f)
                wp, wr = max(wp, p), max(wr, r)
        log(f"  REIMPORT vs stage (bones unconnected, reimport frame = stage frame + {off}), frames {rng[0]}..{rng[1]}: "
            f"max {wp:.6f} mm / {wr:.6f} deg (last worst {at})")


def main():
    preset = write_preset()
    log(f"PRESET {PRESET} written (sha256 {sha(PRESET)}), copied from {GOBLIN_PRESET.name} (sha256 {sha(GOBLIN_PRESET)})")
    kw_exp = preset["export_scene_fbx"]
    kw_imp = preset["blender_reimport"]["import_scene_fbx"]
    log(f"SOURCE {SRC_BLEND} sha256 {sha(SRC_BLEND)}")
    EXPORT.mkdir(parents=True, exist_ok=True)
    p26.build_export(SRC_BLEND, None, STAGE_REST)
    p26.build_export(SRC_BLEND, CLIP, STAGE_CLIP)

    bpy.ops.wm.open_mainfile(filepath=str(STAGE_REST), load_ui=False)
    export_fbx(FBX_BODY, [bpy.data.objects[ARM], bpy.data.objects[MESH]], False, kw_exp)
    bpy.ops.wm.open_mainfile(filepath=str(STAGE_CLIP), load_ui=False)
    sc = bpy.context.scene
    old = sc.name
    sc.name = CLIP
    act = bpy.data.objects[ARM].animation_data.action
    log(f"STAGE {STAGE_CLIP.name}: scene {old!r} -> {sc.name!r} (in memory), action {act.name!r} frames "
        f"{tuple(act.frame_range)}, fps {sc.render.fps}")
    export_fbx(FBX_CLIP, [bpy.data.objects[ARM], bpy.data.objects[MESH]], True, kw_exp)

    for p in (FBX_BODY, FBX_CLIP):
        s = fbx_summary(p)
        log(f"FILE {p.name}: FBX {s['fbx_version']}; header {s['header']}; nodes {s['nodes']}; limb nodes "
            f"{s['limb_nodes']}, _end {s['limb_end_nodes']}; skin clusters {s['skin_clusters']}; materials "
            f"{s['materials']}; anim stacks {s['anim_stacks']}")
    names, parent, stage, rng = stage_world(STAGE_CLIP)
    reimport(FBX_BODY, kw_imp, names, parent)
    reimport(FBX_CLIP, kw_imp, names, parent, stage, rng)

    UNITY_DIR.mkdir(parents=True, exist_ok=True)
    for n in UNITY_REMOVE:
        q = UNITY_DIR / n
        if q.exists():
            q.unlink()
            log(f"REMOVED P1 file {q}")
    for p in (FBX_BODY, FBX_CLIP):
        dst = UNITY_DIR / p.name
        shutil.copy2(p, dst)
        log(f"COPY {p.name} -> {dst} sha256 {sha(dst)}")
    log(f"UNITY Assets/Player now: {sorted(x.name for x in UNITY_DIR.iterdir())}")
    log("DONE")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import traceback
        traceback.print_exc()
        sys.stdout.flush()
        sys.exit(1)
